### ISSUE TITLE
Maybe skip "packages"-folder?

### ISSUE THREAD

**Issue by enkelmedia** [danielsaidi/Cloney#24]
Since lot's of nuget-files are included in a solutions package-folder maybe Cloney should skip the packages folder when performing the clone?

**Comment by enkelmedia** [comment]
I can see that there is a "app.config" with some excludes but this file is not shipped with the binaries on this page: http://danielsaidi.com/Cloney/

**Comment by danielsaidi** [comment]
Thank you!

**Comment by enkelmedia** [comment]
Might be good to dubble check that this config file is include in the next release as well :)
