### ISSUE TITLE
Says it's ready when in fact something went wrong

### ISSUE THREAD

**Issue by enkelmedia** [danielsaidi/Cloney#25]
I just tried to clone a project when the project was open in Visual Studio (guess that's not a good idea but anyway).

The clone started and just some files where transferred before this message was shown:

![cloney error](https://user-images.githubusercontent.com/1782524/75426914-d9ce1a80-5945-11ea-817b-6e7547915994.PNG)

In fact the job stopped at the "storage.ide"-file since it was locked by Visual Studio. I guess that we might be able to come up with a better error message?

**Comment by danielsaidi** [comment]
Solved...by you! :)
